default_platform(:ios)

platform :ios do
  desc "Upload the built IPA to TestFlight"
  lane :upload_testflight do
    api_key = app_store_connect_api_key(
      key_id:      ENV["ASC_KEY_ID"],
      issuer_id:   ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_API_KEY_P8"],
      in_house:    false
    )

    pilot(
      api_key: api_key,
      ipa:     Dir["../build/export/*.ipa"].first,
      skip_waiting_for_build_processing: true
    )
  end
end 